import {
  AlertCircle,
  AlertTriangle,
  ArrowBigUp,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUpRight,
  AudioLines,
  Bell,
  Binary,
  Blocks,
  BookMarked,
  BookOpenText,
  BookmarkPlus,
  Bot,
  BotMessageSquare,
  Boxes,
  Braces,
  BrainCircuit,
  ChartNetwork,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronRightSquare,
  ChevronUp,
  ChevronsDownUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  CircleCheckBig,
  CircleDot,
  CircleOff,
  Clipboard,
  Code,
  Code2,
  CodeXml,
  Cog,
  Columns2,
  Combine,
  Command,
  Compass,
  Copy,
  CopyPlus,
  CornerDownLeft,
  Cpu,
  Database,
  DatabaseZap,
  Delete,
  DollarSign,
  Dot,
  Download,
  DownloadCloud,
  Edit,
  Ellipsis,
  EllipsisVertical,
  Eraser,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileChartColumn,
  FileClock,
  FileCode2,
  FileDown,
  FileJson,
  FilePen,
  FileQuestion,
  FileSearch,
  FileSearch2,
  FileSliders,
  FileText,
  FileType,
  FileType2,
  FileUp,
  FlaskConical,
  FolderIcon,
  FolderPlus,
  FolderPlusIcon,
  FolderSync,
  FolderUp,
  FormInput,
  Forward,
  Gift,
  GitBranchPlus,
  GitFork,
  Globe,
  GripVertical,
  Group,
  Hammer,
  Heart,
  HelpCircle,
  Home,
  Image,
  Infinity,
  Info,
  Key,
  Keyboard,
  Laptop2,
  Layers,
  LayoutGrid,
  LayoutPanelTop,
  Link,
  Link2,
  List,
  ListChecks,
  ListFilter,
  ListOrdered,
  ListX,
  Loader2,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  LucideSend,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareMore,
  MessagesSquare,
  Mic,
  Mic2,
  MicOff,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoonIcon,
  MoreHorizontal,
  Network,
  Newspaper,
  NotebookPen,
  OctagonAlert,
  OptionIcon,
  Package2,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  PaperclipIcon,
  Pen,
  Pencil,
  PencilLine,
  PencilRuler,
  PieChart,
  Pin,
  Plane,
  Play,
  Plus,
  PlusCircle,
  PlusSquare,
  PocketKnife,
  Radio,
  Redo,
  RefreshCcw,
  RefreshCcwDot,
  Repeat,
  Replace,
  RotateCcw,
  Save,
  SaveAll,
  Scan,
  ScanEye,
  Scissors,
  ScreenShare,
  Scroll,
  ScrollText,
  Search,
  Settings,
  Settings2,
  Share,
  Share2,
  Shield,
  Sigma,
  Sliders,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Square,
  SquareArrowOutUpRight,
  SquareCode,
  SquarePen,
  SquarePlay,
  StickyNote,
  Store,
  Sun,
  SunIcon,
  Table,
  Tags,
  TerminalIcon,
  TerminalSquare,
  TextCursorInput,
  TextSearch,
  TextSearchIcon,
  ThumbsDown,
  ThumbsUp,
  ToyBrick,
  Trash2,
  Type,
  Undo,
  Ungroup,
  Unplug,
  Upload,
  User,
  UserCog2,
  UserMinus2,
  UserPlus2,
  Users,
  Users2,
  Variable,
  Wand2,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import { iconsType } from "../types/components";

export const gradients = [
  "bg-linear-to-br from-gray-800 via-rose-700 to-violet-900",
  "bg-linear-to-br from-green-200 via-green-300 to-blue-500",
  "bg-linear-to-br from-yellow-200 via-yellow-400 to-yellow-700",
  "bg-linear-to-br from-green-200 via-green-400 to-purple-700",
  "bg-linear-to-br from-blue-100 via-blue-300 to-blue-500",
  "bg-linear-to-br from-purple-400 to-yellow-400",
  "bg-linear-to-br from-red-800 via-yellow-600 to-yellow-500",
  "bg-linear-to-br from-blue-300 via-green-200 to-yellow-300",
  "bg-linear-to-br from-blue-700 via-blue-800 to-gray-900",
  "bg-linear-to-br from-green-300 to-purple-400",
  "bg-linear-to-br from-yellow-200 via-pink-200 to-pink-400",
  "bg-linear-to-br from-green-500 to-green-700",
  "bg-linear-to-br from-rose-400 via-fuchsia-500 to-indigo-500",
  "bg-linear-to-br from-sky-400 to-blue-500",
  "bg-linear-to-br from-green-200 via-green-400 to-green-500",
  "bg-linear-to-br from-red-400 via-gray-300 to-blue-500",
  "bg-linear-to-br from-gray-900 to-gray-600 bg-linear-to-r",
  "bg-linear-to-br from-rose-500 via-red-400 to-red-500",
  "bg-linear-to-br from-fuchsia-600 to-pink-600",
  "bg-linear-to-br from-emerald-500 to-lime-600",
  "bg-linear-to-br from-rose-500 to-indigo-700",
  "bg-linear-to-br bg-linear-to-tr from-violet-500 to-orange-300",
  "bg-linear-to-br from-gray-900 via-purple-900 to-violet-600",
  "bg-linear-to-br from-yellow-200 via-red-500 to-fuchsia-500",
  "bg-linear-to-br from-sky-400 to-indigo-900",
  "bg-linear-to-br from-amber-200 via-violet-600 to-sky-900",
  "bg-linear-to-br from-amber-700 via-orange-300 to-rose-800",
  "bg-linear-to-br from-gray-300 via-fuchsia-600 to-orange-600",
  "bg-linear-to-br from-fuchsia-500 via-red-600 to-orange-400",
  "bg-linear-to-br from-sky-400 via-rose-400 to-lime-400",
  "bg-linear-to-br from-lime-600 via-yellow-300 to-red-600",
];

/*
Specifications
#FF3276 -> #F480FF
#1A0250 -> #2F10FE
#98F4FE -> #9BFEAA
#F480FF -> #7528FC
#F480FF -> #9BFEAA
#2F10FE -> #9BFEAA
#BB277F -> #050154
#7528FC -> #9BFEAA
#2F10FE -> #98F4FE
*/
export const flowGradients = [
  "linear-gradient(90deg, #FF3276 0%, #F480FF 100%)",
  "linear-gradient(90deg, #1A0250 0%, #2F10FE 100%)",
  "linear-gradient(90deg, #98F4FE 0%, #9BFEAA 100%)",
  "linear-gradient(90deg, #F480FF 0%, #7528FC 100%)",
  "linear-gradient(90deg, #F480FF 0%, #9BFEAA 100%)",
  "linear-gradient(90deg, #2F10FE 0%, #9BFEAA 100%)",
  "linear-gradient(90deg, #BB277F 0%, #050154 100%)",
  "linear-gradient(90deg, #7528FC 0%, #9BFEAA 100%)",
  "linear-gradient(90deg, #2F10FE 0%, #98F4FE 100%)",
];

export const toolModeGradient =
  "linear-gradient(-60deg,var(--tool-mode-gradient-1) 0%,var(--tool-mode-gradient-2) 100%)";

export const swatchColors = [
  "bg-neon-fuschia text-white",
  "bg-digital-orchid text-plasma-purple",
  "bg-plasma-purple text-digital-orchid",
  "bg-electric-blue text-holo-frost",
  "bg-holo-frost text-electric-blue",
  "bg-terminal-green text-cosmic-void",
];

export const nodeColors: { [char: string]: string } = {
  inputs: "#10B981",
  outputs: "#AA2411",
  data: "#198BF6",
  prompts: "#4367BF",
  models: "#ab11ab",
  model_specs: "#6344BE",
  chains: "#FE7500",
  list: "#9AAE42",
  agents: "#903BBE",
  Olivya: "#00413B",
  tools: "#00fbfc",
  memories: "#F5B85A",
  saved_components: "#a5B85A",
  advanced: "#000000",
  chat: "#198BF6",
  thought: "#272541",
  embeddings: "#42BAA7",
  documentloaders: "#7AAE42",
  vectorstores: "#AA8742",
  vectorsearch: "#AA8742",
  textsplitters: "#B47CB5",
  toolkits: "#DB2C2C",
  wrappers: "#E6277A",
  notion: "#000000",
  Notion: "#000000",
  AssemblyAI: "#213ED7",
  assemblyai: "#213ED7",
  helpers: "#31A3CC",
  prototypes: "#E6277A",
  astra_assistants: "#272541",
  langchain_utilities: "#31A3CC",
  output_parsers: "#E6A627",
  // custom_components: "#ab11ab",
  retrievers: "#e6b25a",
  str: "#4F46E5",
  Text: "#4F46E5",
  unknown: "#9CA3AF",
  Document: "#65a30d",
  Data: "#dc2626",
  Message: "#4f46e5",
  Prompt: "#7c3aed",
  Embeddings: "#10b981",
  BaseLanguageModel: "#c026d3",
  LanguageModel: "#c026d3",
  Agent: "#903BBE",
  AgentExecutor: "#903BBE",
  Tool: "#00fbfc",
};

export const nodeColorsName: { [char: string]: string } = {
  // custom_components: "#ab11ab",
  inputs: "emerald",
  outputs: "red",
  data: "sky",
  prompts: "blue",
  models: "fuchsia",
  model_specs: "violet",
  chains: "orange",
  list: "lime",
  agents: "purple",
  tools: "cyan",
  memories: "amber",
  saved_components: "lime",
  advanced: "slate",
  chat: "sky",
  thought: "zinc",
  embeddings: "teal",
  documentloaders: "lime",
  vectorstores: "yellow",
  vectorsearch: "yellow",
  textsplitters: "fuchsia",
  toolkits: "red",
  wrappers: "rose",
  notion: "slate",
  Notion: "slate",
  AssemblyAI: "blue",
  assemblyai: "blue",
  helpers: "cyan",
  prototypes: "rose",
  astra_assistants: "indigo",
  langchain_utilities: "sky",
  output_parsers: "yellow",
  retrievers: "yellow",
  str: "indigo",
  Text: "indigo",
  unknown: "gray",
  Document: "lime",
  Data: "red",
  Message: "indigo",
  Prompt: "violet",
  Embeddings: "emerald",
  BaseLanguageModel: "fuchsia",
  LanguageModel: "fuchsia",
  Agent: "purple",
  AgentExecutor: "purple",
  Tool: "cyan",
  BaseChatMemory: "cyan",
  BaseChatMessageHistory: "orange",
  Memory: "orange",
  DataFrame: "pink",
};

export const FILE_ICONS = {
  json: {
    icon: "FileJson",
    color: "text-datatype-indigo dark:text-datatype-indigo-foreground",
  },
  csv: {
    icon: "FileChartColumn",
    color: "text-datatype-emerald dark:text-datatype-emerald-foreground",
  },
  txt: {
    icon: "FileType",
    color: "text-datatype-purple dark:text-datatype-purple-foreground",
  },
  pdf: {
    icon: "File",
    color: "text-datatype-red dark:text-datatype-red-foreground",
  },
};

export const SIDEBAR_CATEGORIES = [
  { display_name: "Saved", name: "saved_components", icon: "GradientSave" },
  { display_name: "Inputs", name: "inputs", icon: "Download" },
  { display_name: "Outputs", name: "outputs", icon: "Upload" },
  { display_name: "Prompts", name: "prompts", icon: "TerminalSquare" },
  { display_name: "Data", name: "data", icon: "Database" },
  { display_name: "Processing", name: "processing", icon: "ListFilter" },
  { display_name: "Models", name: "models", icon: "BrainCircuit" },
  { display_name: "Vector Stores", name: "vectorstores", icon: "Layers" },
  { display_name: "Embeddings", name: "embeddings", icon: "Binary" },
  { display_name: "Agents", name: "agents", icon: "Bot" },
  { display_name: "Chains", name: "chains", icon: "Link" },
  { display_name: "Loaders", name: "documentloaders", icon: "Paperclip" },
  { display_name: "Link Extractors", name: "link_extractors", icon: "Link2" },
  { display_name: "Memories", name: "memories", icon: "Cpu" },
  { display_name: "Output Parsers", name: "output_parsers", icon: "Compass" },
  { display_name: "Prototypes", name: "prototypes", icon: "FlaskConical" },
  { display_name: "Retrievers", name: "retrievers", icon: "FileSearch" },
  { display_name: "Text Splitters", name: "textsplitters", icon: "Scissors" },
  { display_name: "Toolkits", name: "toolkits", icon: "Package2" },
  { display_name: "Tools", name: "tools", icon: "Hammer" },
  { display_name: "Logic", name: "logic", icon: "ArrowRightLeft" },
  { display_name: "Helpers", name: "helpers", icon: "Wand2" },
];

export const SIDEBAR_BUNDLES = [
  { display_name: "Gmail", name: "gmail", icon: "Gmail" },
  // Add apify
  { display_name: "Apify", name: "apify", icon: "Apify" },
  { display_name: "LangChain", name: "langchain_utilities", icon: "LangChain" },
  { display_name: "AgentQL", name: "agentql", icon: "AgentQL" },
  { display_name: "AssemblyAI", name: "assemblyai", icon: "AssemblyAI" },
  {
    display_name: "DataStax",
    name: "astra_assistants",
    icon: "AstraDB",
  },
  { display_name: "Olivya", name: "olivya", icon: "Olivya" },
  { display_name: "LangWatch", name: "langwatch", icon: "Langwatch" },
  { display_name: "Notion", name: "Notion", icon: "Notion" },
  { display_name: "Needle", name: "needle", icon: "Needle" },
  { display_name: "NVIDIA", name: "nvidia", icon: "NVIDIA" },
  { display_name: "Vectara", name: "vectara", icon: "Vectara" },
  { display_name: "Icosa Computing", name: "icosacomputing", icon: "Icosa" },
  { display_name: "Google", name: "google", icon: "Google" },
  { display_name: "CrewAI", name: "crewai", icon: "CrewAI" },
  { display_name: "NotDiamond", name: "notdiamond", icon: "NotDiamond" },
  { display_name: "Composio", name: "composio", icon: "Composio" },
  { display_name: "Cohere", name: "cohere", icon: "Cohere" },
  { display_name: "Firecrawl", name: "firecrawl", icon: "FirecrawlCrawlApi" },
  { display_name: "Unstructured", name: "unstructured", icon: "Unstructured" },
  { display_name: "Git", name: "git", icon: "GitLoader" },
  { display_name: "Confluence", name: "confluence", icon: "Confluence" },
  { display_name: "Mem0", name: "mem0", icon: "Mem0" },
  { display_name: "Youtube", name: "youtube", icon: "YouTube" },
  { display_name: "ScrapeGraph AI", name: "scrapegraph", icon: "ScrapeGraph" },
];

export const categoryIcons = {
  inputs: Download,
  outputs: Upload,
  prompts: TerminalSquare,
  data: Database,
  models: BrainCircuit,
  helpers: Wand2,
  vectorstores: Layers,
  embeddings: Binary,
  agents: Bot,
  astra_assistants: Sparkles,
  chains: Link,
  documentloaders: Paperclip,
  langchain_utilities: PocketKnife,
  link_extractors: Link2,
  memories: Cpu,
  output_parsers: Compass,
  prototypes: FlaskConical,
  retrievers: FileSearch,
  textsplitters: Scissors,
  toolkits: Package2,
  tools: Hammer,
  custom: Edit,
};

export const nodeIconsLucide: iconsType = {
  //Category Icons
  inputs: Download,
  outputs: Upload,
  prompts: TerminalSquare,
  data: Database,
  models: BrainCircuit,
  helpers: Wand2,
  vectorstores: Layers,
  embeddings: Binary,
  agents: Bot,
  astra_assistants: Sparkles,
  chains: Link,
  documentloaders: Paperclip,
  langchain_utilities: PocketKnife,
  link_extractors: Link2,
  memories: Cpu,
  output_parsers: Compass,
  prototypes: FlaskConical,
  retrievers: FileSearch,
  textsplitters: Scissors,
  toolkits: Package2,
  tools: Hammer,
  ChatInput: MessagesSquare,
  ChatOutput: MessagesSquare,
  //Integration Icons
  Notify: Bell,
  ListFlows: Group,
  ClearMessageHistory: FileClock,
  //Node Icons
  model_specs: FileSliders,
  advanced: Laptop2,
  chat: MessageCircle,
  vectorsearch: TextSearch,
  wrappers: Gift,
  unknown: HelpCircle,
  custom: Edit,
  Keyboard,
  ArrowRight,
  Play,
  CheckCheck,
  ListFilter,
  ScrollText,
  Workflow,
  User,
  ScanEye,
  Type,
  FolderIcon,
  X,
  Trash2,
  CircleOff,
  Boxes,
  Network,
  XCircle,
  Info,
  CheckCircle2,
  FileJson,
  FileChartColumn,
  FileType,
  File,
  SquarePen,
  Zap,
  MessagesSquare,
  ExternalLink,
  ChevronsUpDown,
  Check,
  Home,
  Users2,
  SunIcon,
  MoonIcon,
  Bell,
  AlertTriangle,
  ChevronLeft,
  SlidersHorizontal,
  Palette,
  RefreshCcwDot,
  FolderUp,
  SquarePlay,
  LayoutPanelTop,
  Database,
  Blocks,
  ChevronDown,
  ArrowLeft,
  BrainCircuit,
  Wand2,
  Layers,
  Binary,
  Paperclip,
  PocketKnife,
  Scissors,
  Cpu,
  Hammer,
  Shield,
  NotebookPen,
  Plus,
  Redo,
  Settings2,
  FileType2,
  Undo,
  FileSearch2,
  ChevronRight,
  Circle,
  CircleDot,
  Clipboard,
  PlusCircle,
  PlusSquare,
  Code2,
  Globe,
  Variable,
  Snowflake,
  Store,
  Download,
  Replace,
  Eraser,
  Lock,
  LockOpen,
  ListX,
  Newspaper,
  Tags,
  CodeXml,
  PieChart,
  LucideSend,
  Sparkles,
  DownloadCloud,
  FileText,
  FolderPlus,
  GitFork,
  FileDown,
  FilePen,
  FileUp,
  Menu,
  Save,
  Search,
  Copy,
  Upload,
  MessageSquare,
  MoreHorizontal,
  UserMinus2,
  UserPlus2,
  Pencil,
  PencilRuler,
  ChevronsRight,
  ChevronsLeft,
  EyeOff,
  Eye,
  UserCog2,
  Key,
  Unplug,
  Group,
  LogIn,
  ChevronUp,
  PencilLine,
  Ungroup,
  BookMarked,
  Minus,
  LogOut,
  BotMessageSquare,
  Square,
  Minimize2,
  Maximize2,
  FormInput,
  ChevronRightSquare,
  Plane,
  Users,
  ListOrdered,
  SaveAll,
  MessageSquareMore,
  Forward,
  Share2,
  Share,
  GitBranchPlus,
  Infinity,
  Loader2,
  BookmarkPlus,
  Heart,
  Package2,
  FileSearch,
  Compass,
  Link2,
  Pin,
  Link,
  ToyBrick,
  RefreshCcw,
  SquareArrowOutUpRight,
  Combine,
  TerminalIcon,
  TerminalSquare,
  TextCursorInput,
  Repeat,
  Sliders,
  ScreenShare,
  Code,
  OctagonAlert,
  Ellipsis,
  Braces,
  FlaskConical,
  AlertCircle,
  Bot,
  EllipsisVertical,
  Delete,
  Command,
  ArrowBigUp,
  PanelRightClose,
  Dot,
  LayoutGrid,
  StickyNote,
  note: StickyNote,
  RotateCcw,
  Wrench,
  GripVertical,
  FolderPlusIcon,
  PaperclipIcon,
  Settings,
  Monitor,
  Moon,
  Sun,
  PanelLeftClose,
  PanelLeftOpen,
  ArrowUpRight,
  Scroll,
  Image,
  CopyPlus,
  Pen,
  TextSearchIcon,
  FileQuestion,
  List,
  SquareCode,
  ListChecks,
  PanelRightOpen,
  CornerDownLeft,
  ChevronsDownUp,
  OptionIcon,
  ChartNetwork,
  Option: OptionIcon,
  Table,
  Scan,
  CircleCheckBig,
  ZoomIn,
  ZoomOut,
  Sigma,
  Radio,
  DatabaseZap,
  Cog,
  ArrowRightLeft,
  FolderSync,
  ThumbsUp,
  ThumbsDown,
  FileCode2,
  Columns2,
  Mic,
  MicOff,
  Mic2,
  DollarSign,
  BookOpenText,
  AudioLines,
};
